vtex-sites/starter.store

.gitignore
Add .faststore folder to .gitignore
=> fix: add .faststore folder to .gitignore

package.json, yarn.lock
This PR updates the core package implementing the breadcrumb component.
https://github.com/vtex/faststore/pull/1635
Signed-off-by: Arthur Andrade <arthurfelandrade@gmail.com>
=> feat: update core with `Breadcrumb`component

package.json, yarn.lock
- Updates the core version adding `SearchProductCard `
reference: https://github.com/vtex/faststore/pull/1640
=> chore: Updates version with `SearchProductCard`

faststore.config.js, package.json, yarn.lock
Updates faststore package to the latest one.
SearchSuggestions, SearchTop,  SearchHistory and SlideOver updates should be available.
=> chore: Updates package version

.github/CODEOWNERS, .github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/documentation-request.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/question.md, .github/PULL_REQUEST_TEMPLATE.md
Creates the template files for Github PR/Issues, and CODEOWNER file.
=> chore: adds GH template files and Codeowners

package.json, yarn.lock
Updates the core version adding `Toast` component .
Use [deploy preview](https://preview-22--starter.preview.vtex.app/) to test. Everything should be the same as before.
https://github.com/vtex/faststore/pull/1672
=> chore: Updates with `Toast` component

package.json, yarn.lock
Updates the core version adding the following features:
- `Filter` and `FilterSlider` component
- `SkuSelector` component
- `OutOfStock` component 
- `ShippingSimulation` component 
- `RegionBar` component 
- `Search` feature (SearchInput, SearchInputField and SearchDropdown components)
You can use the [preview link](https://sfj-5764503--starter.preview.vtex.app/) to test all the features listed above.
- Filter https://github.com/vtex/faststore/pull/1687
- ShippingSimulation https://github.com/vtex/faststore/pull/1689
- SkuSelector https://github.com/vtex/faststore/pull/1677
- OutOfStock  https://github.com/vtex/faststore/pull/1685
- RegionBar https://github.com/vtex/faststore/pull/1693
- Search feature https://github.com/vtex/faststore/pull/1676
=> Feat: Adds `Filter`, `FilterSlider`, `ShippingSimulation`, `SkuSelector`, `OutOfStock`,  `RegionBar` and `Search` features

README.md, package.json, yarn.lock
Updates the core version, including changes from https://github.com/vtex/faststore/pull/1704/
Check the deploy preview. The `CartSidebar` should remain the same.
https://github.com/vtex/faststore/pull/1704/
=> Feat:  Adds `CartSidebar` component

package.json, yarn.lock
Updates the `@faststore/core` version to add the `ImageGallery` component.
Build and check the store on PDP if the `ImageGallery` component it's rendering as it should.
- [Feat: Add ImageGallery components](https://github.com/vtex/faststore/pull/1681)
=> feat: Adds `ImageGallery` component

package.json, yarn.lock
Updates the @faststore/core version to add the `EmptyState` component.
Build and check the itens below:
a. Open the CartSidebar when the cart has no items.
b. Search for Gallery using the search input.
c. Try the Not Found: 404 page
https://github.com/vtex/faststore/pull/1716
=> Feat: Adds `EmptyState` component

package.json, yarn.lock
Updates the `@faststore/core` version to add the `ProductShelf` and `ProductGrid` components.
1. Build and check the store's Homepage if the `ProductShelf` component it's rendering as it should.
2. Build and check the store's PLP if the `ProductGrid` component it's rendering as it should.
- https://github.com/vtex/faststore/pull/1713
- https://github.com/vtex/faststore/pull/1719
=> feat: Adds `ProductGrid` component

package.json, yarn.lock
Updates the `@faststore/core` version to add the `Navbar`, `NavbarLinks` and `NavbarSlider` and their components.
Build and check the if the navbar on any store page if it's rendering as it should.
- [feat: Adds `Navbar` component](https://github.com/vtex/faststore/pull/1728)
=> feat: Adds `Navbar` component

package.json, yarn.lock
Update content-types
https://github.com/vtex/faststore/pull/1745
=> feat: Add Product list Page content type

package.json, yarn.lock
Updates core version to 2.0.137-alpha.0
=> chore: update core version to 2.0.137-alpha.0

package.json, yarn.lock
This PR intends to update the `@faststore/core` package with [FS: Adjust Navbar for CMS](https://github.com/vtex/faststore/pull/1756) changes.
- Check the Home page and if `Navbar` it's working as expected.
=> feat: Adjust `Navbar` for CMS

package.json, yarn.lock
Updates starter with changes from  https://github.com/vtex/faststore/pull/1767
you can use the preview link with the query parameters generated from https://formspace--storeframework.myvtex.com/admin/new-cms/faststore/page/edit/bd9e01c6-534e-4e54-aa76-f864dcbad024/
https://github.com/vtex/faststore/pull/1767
=> Feat: Hero from CMS in PLP

package.json, yarn.lock
🎗️ Remember to update the version after faststore pr is merged so that we can get all updated improvements (e.g. the ones from LH).
Changes from https://github.com/vtex/faststore/pull/1754
install dependencies
`yarn`
test the store scripts
`yarn dev`
`yarn build && yarn start`
https://github.com/vtex/faststore/pull/1754
=> fix: Windows-fix: use path instead of / for handling paths

package.json, yarn.lock
This PR intends to update the `@faststore/core` version which fixes the integration tests and some components' issues.
https://github.com/vtex/faststore/pull/1772
=> fix: Integration tests

package.json, yarn.lock
Temporarily skip flaky tests.
- https://github.com/vtex/faststore/pull/1808
=> chore: temp skip flaky tests

faststore.config.js, package.json
This PR intends to update the `faststore.config` after run build.
=> chore: Updates `faststore.config`

package.json, yarn.lock
=> fix: Skip integration tests

package.json, yarn.lock
Create a new script called cms-sync in order to prevent the user from entering the temporary folder so that the script can run.
=> feat: new script to sync cms

package.json, yarn.lock
follow up from 
- https://github.com/vtex/faststore/pull/1856
after running
```cms
npx update-browserslist-db@latest
```
|Before|After|
|-|-|
|![Screenshot 2023-06-28 at 14 21 48](https://github.com/vtex-sites/starter.store/assets/11325562/beebe01d-3d32-4d6d-9d91-2b1d341e22d2)|<img width="1598" alt="Screenshot 2023-06-28 at 14 23 43" src="https://github.com/vtex-sites/starter.store/assets/11325562/1632a34a-1a60-47d0-b459-d3f1376ca7ee">|
=> chore: updates caniuse with npx update-browserslist-db@latest

package.json, yarn.lock
Related to [faststore#1892](https://github.com/vtex/faststore/pull/1892)
=> fix: PLP integration tests

package.json, yarn.lock
This PR attempts to update starter version adding the following changes:
[Fix: Carousel and ProductShelf bugs #1932](https://github.com/vtex/faststore/pull/1932 )
[Fix: Allow update shippingData for loggedIn User #1952](https://github.com/vtex/faststore/pull/1952)
[Fix: Improves ProductTitle Accessibility](https://github.com/vtex/faststore/pull/1957)
[Fix: Update Shipping Data from OrderForm #1960](https://github.com/vtex/faststore/pull/1960)
[[TCM-101] Delete translation-keys.json file #1956](https://github.com/vtex/faststore/pull/1956)
[TCM-101]: https://vtex-dev.atlassian.net/browse/TCM-101?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: Updates packages version

package.json, yarn.lock
https://github.com/vtex/faststore/pull/1948
=> feat: Expose account and engine in Window variable

package.json, yarn.lock
https://github.com/vtex/faststore/pull/1949
=> fix: SKU overflow in PDP

package.json, yarn.lock
https://github.com/vtex/faststore/pull/1950
=> fix: Nested footer elements

package.json, yarn.lock
This PR updates `@faststore/cli` package with vtex/faststore#1982 changes.
=> chore: Update `@faststore/cli` version

package.json, yarn.lock
Updates `fs/core` package with https://github.com/vtex/faststore/pull/1974 fixes.
=> Fix: Native icons do not display in Firefox

faststore.config.js, package.json, yarn.lock
- Updates core package version to `^2.1.78`
Applies the changes below:
- https://github.com/vtex-sites/starter.store/pull/153
- https://github.com/vtex/faststore/pull/1963
- https://github.com/vtex-sites/starter.store/pull/161
=> Chore: Update core package version to 2.1.78

package.json, yarn.lock
Applies changes from:
- https://github.com/vtex-sites/starter.store/pull/176
- https://github.com/vtex-sites/starter.store/pull/177
=> Fix: Accessibility improvements

package.json, yarn.lock
- Updates starter to apply changes from https://github.com/vtex/faststore/pull/1980
- Customers now can add external third-party scripts (Sample: https://github.com/vtex-sites/starter.store/pull/174)
- Official documentation is coming soon
=> Feat: Support Third-Party Script 

package.json, yarn.lock
Applies changes from https://github.com/vtex/faststore/pull/2012
=> Chore: Sets FS session cookies

package.json, yarn.lock
Check the PDP e see if everything is fine, also try to access a product with an unavailable SKU to check the `Not Available` button.
|Before|After|
|-|-|
|<img width="416" alt="Screenshot 2023-09-19 at 13 04 20" src="https://github.com/vtex/faststore/assets/11325562/9573b7bf-4f0d-48f6-a367-732b491141eb">|<img width="412" alt="Screenshot 2023-09-19 at 13 03 16" src="https://github.com/vtex/faststore/assets/11325562/e83d5cca-adc4-49a0-b1fb-7b7c94a2538f">|
https://github.com/vtex/faststore/pull/2031
=> chore: `NotAvailable` button product

package.json, yarn.lock
- Applies changes from https://github.com/vtex/faststore/commit/64e6c01df82180f120be2a2ac5a1a5aae0cdd590
- Updates package version to ^2.1.107
=> Fix: Scroll restoration & updates package version to ^2.1.107 

faststore.config.js
This PR sets the Node version to 18.
=> chore: Set Node 18

package.json, yarn.lock
=> fix: Updates faststore packages

package.json, yarn.lock
Applies changes from https://github.com/vtex/faststore/pull/2108
=> feat: Adds target="_blank" to Hero & Banner - Updates @faststore/core to 2.2.37

package.json, yarn.lock
Applies changes from https://github.com/vtex/faststore/pull/2062
=> chore: Adds carousel itemsPerPage field in CMS 

package.json, yarn.lock
Upgrades all FastStore packages to latest version at the moment.
=> chore: upgrade faststore packages to 2.2.46

package.json, yarn.lock
=> upgrade packages to 2.2.48

package.json, yarn.lock
=> Test forwarded host

package.json, yarn.lock
This reverts commit 88c410ebe3fb957e00f74a4385c55b32d2c218d7.
=> Revert "test forwarded host (#312)"

package.json, yarn.lock
=> test ownership cookie fix

package.json, yarn.lock
use version of
- https://github.com/vtex/faststore/pull/2158
=> chore: adjusts replace existingCookie with storageCookieValue

package.json, yarn.lock
Upgrades FastStore Packages to their latest versions
https://github.com/vtex/faststore/pull/2158
=> chore: upgrade packages to 2.2.49

package.json, yarn.lock
This PR updates faststore version to v3.
Check the preview link
- https://github.com/vtex/faststore/pull/2214
=> Feat: uses FastStore core v2

package.json, yarn.lock
Problem detected at the formation of cookies between version 3.0.24 and 3.0.26 at the core package.
=> Update packages version from starter

package.json, yarn.lock
applies changes from
- https://github.com/vtex/faststore/pull/2278
=> fix: Checkout and FastStore minicart sync

package.json, yarn.lock
Applies changes from 
- https://github.com/vtex/faststore/pull/2279
=> chore: ensure generate the cms webhook file in generate method

package.json, yarn.lock
Test 
- https://github.com/vtex/faststore/pull/2305
=> feat: adds sections to pages

package.json, yarn.lock
=> Test change on API package

package.json, yarn.lock
Reverts vtex-sites/starter.store#476
=> Revert "Test change on API package"

package.json, yarn.lock
=> Update faststore/core to 3.0.73

faststore.config.js
=> chore: Updates name settings

.github/dependabot.yml
Updates Dependabot file attempts to run because it's stuck at 'Checking now' for a while.
=> docs: small adjustment

README.md, package.json, yarn.lock
=> FastStore(deps): Bump @faststore/cli from 3.0.159 to 3.1.2

package.json, yarn.lock
=> FastStore(deps): Bump @faststore/cli from 3.1.2 to 3.4.0
