vtex-sites/starter.store

package.json, yarn.lock
https://github.com/vtex/faststore/pull/1661
- you can use the **starter PR preview** and check if the images are working as expected webp format and HIT the Cloudfront cache in Devtols response Headers
- you can run `yarn build && yarn start` locally and test the images from all the pages. Check Devtools tab, filter img and double-check the domain, type, size, and time for each image, along with the cache from the response headers.
(expected webp format and HIT the Cloudfront cache).
- Doc (Internal use, ask me using slack channel).
https://nextjs.org/docs/messages/sharp-missing-in-production
https://nextjs.org/docs/api-reference/next/image#loader
https://nextjs.org/docs/basic-features/image-optimization#loaders
https://nextjs.org/docs/api-reference/next/image#loader-configuration …
=> Feat: Image using next/future/image + new Thumbor URL

package.json, yarn.lock
Starter PR from https://github.com/vtex/faststore/pull/1712
It prepares the repo to uses the CMS Section approach. It also enables the CSS Modules per section instead of importing all styles globally as before. Finally it fixes the Unused CSS Problem for Homepage, PDP, PLP, Search etc.
All the pages should keep the same visually in Desktop and Mobile versions. You can see the coverage tab in devtools and check the unused CSS compared to previous version using the starter PR.
https://github.com/vtex/faststore/pull/1712
=> Fix: LH Unused CSS + Organizes CMS Sections and components styles.

package.json, yarn.lock
Updates core package with https://github.com/vtex/faststore/pull/1747 changes
You may notice that in some pages (e.g. PDP) the breadcrumb is not shown. That's because CMS team is investigating some behaviors and maybe the Breadcrumb section [is not present in CMS](https://storeframework.myvtex.com/admin/new-cms/faststore/pdp/edit/717bc97f-8f19-4744-a52b-7ccac43cc898/).
- check the breadcrumb in PDP, PLP and Search Pages. you can also see the starter preview.
https://github.com/vtex/faststore/pull/1747
=> Feat: Pages with `RenderSection` + `Breadcrumb` section CMS

.github/dependabot.yml
- removes dependabot Evergreen label and prefix from the dependabot PR and email sent as notification.
=> chore: removes dependabot Evergreen label and prefix

cms-webhook-urls.json, faststore.config.js, package.json, yarn.lock
Uses the new `vtexHeadlessCms` config.
- Run `yarn dev` or `yarn build` and check the hidden `.faststore` folder, the file `cms-webhook-urls.json` should be there.
https://github.com/vtex/faststore/pull/1829
=> feat: Generates CMS webhook URLs json file from the store's config

.github/dependabot.yml
Fix 
```cmd
The property '#/updates/0/commit-message' has a property 'include' that depends on a missing property 'prefix'
```
from
[see the commit-message docs](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#commit-message)
=> Fix: Update dependabot.yml

package.json, yarn.lock
- When running cli `faststore cms-sync`, runs `generate` to ensure that sections and content-types files are merged or check if anything else is needed before calling `cms-sync`.
- We were having some issues because the `mergeCMSFiles` were only called when running `yarn dev` in the application, and the users couldn't see the changes made on the repository when sync with CMS. To avoid issues like that, it would be nice if `faststore cms-sync` checked it.
https://github.com/vtex/faststore/pull/1877
=> Chore: Updates `faststore cms-sync` cli command

package.json, yarn.lock
This should be a temporary solution
We are currently trying different approaches to run our platform integration tests smoothly.
Skipping it now should be temporary.
Meanwhile can try [Customizing you own test](https://www.faststore.dev/docs/faststore-config-options/custom-cypress-test)
https://github.com/vtex/faststore/pull/1968
=> chore: Skip integration tests

package.json, yarn.lock
Updates core and api packages to `2.1.91`, applies changes below:
🔧 Fix FastStore person identification 
🔧 Fix slug path when a page is created in headless CMS with more than one path parameter
- https://github.com/vtex/faststore/pull/2013
- https://github.com/vtex/faststore/pull/2021
=> Chore: Updates core and api packages to 2.1.91

package.json, yarn.lock
This PR intends to fix a wrong QuantitySelector behavior when navigating between PDPs.
Currently, if the user increase the product's quantity then clicks on any product inside the "People also bought" section (on the current PDP) the counter isn't reset
- Go to any PDP;
- Increase the product's quantity;
- Click on any product inside the "People also bought" section".
The product's quantity should be 1.
https://github.com/vtex/faststore/pull/2043
=> fix: Reset `QuantitySelector` counter when navigating between PDPs

package.json, yarn.lock
Applies changes from https://github.com/vtex/faststore/pull/2045
- Fix PLP bug when navigating through different PLPs w/ additional pages. The loaded pages in the PLP are not being reset, and there are no products to show; it displays a list of the Product's card skeleton.
|Bug - Before|
|-|
|![bug-plp-before](https://github.com/vtex/faststore/assets/3356699/04e3fb12-73f3-4e90-890e-fd991678514f)|![bug-plp-fix](https://github.com/vtex/faststore/assets/3356699/306d3920-fe9a-4c95-8d66-9bc9dc1bc1fa)|
|After|
|-|
|![bug-plp-fix](https://github.com/vtex/faststore/assets/3356699/306d3920-fe9a-4c95-8d66-9bc9dc1bc1fa)|
1. Click on the `Office` category in the Navbar
2. Click twice on the `Load more products` button; it should load 3 pages In the PLP
3. Now, click in the `Technology` category in …
=> fix: PLP when navigating through different PLPs w/ additional pages

.gitignore
Since we are allowing the use of the [public](https://github.com/vtex/faststore/pull/2078) folder, we can remove it from the gitigone list.
=> chore: Removes public folder from gitignore

package.json, yarn.lock
Applies changes from [Feat: add ICO extension support to public files copy](https://github.com/vtex/faststore/pull/2116)
modify favicon.ico in app's /public dir, run build, verify that change is propagated through to favicon in browser
=> feat: Updates @faststore/cli to 2.2.26 

package.json, yarn.lock
Applies fixes from [fix: alert types #2124](https://github.com/vtex/faststore/pull/2124)
=> fix: Fixes Alert Types - Updates @faststore/core to 2.2.32

package.json, yarn.lock
Related to PR:
https://github.com/vtex/faststore/pull/2159
Remove orderFormId param from /account and /login
This param should not be sent when the user is navigating to those pages.
Go to my account and check if the param is passed at the URL.
WIP
The logic to get this param and add to the session was removed at this PR:
https://github.com/vtex/admin-faststore/pull/25
=> Remove: OrderFormId param from /acount and /login

package.json, yarn.lock
- Adds `EmptyGallery` section in `ProductGallery`
- Enables EmptyGallery to be customizable through CMS
- you can use this workspace to make changes via CMS: https://fanny--storeframework.myvtex.com/admin/new-cms/faststore/search/
- run locally this branch and use the preview in the workspace above
- you should be able to see the changes applied locally
- You can search for "a" in the `InputSearch` to see this `EmptyGallery` component.
https://github.com/vtex/faststore/pull/2148
=> Feat: Make empty gallery customizable through the CMS

package.json
Although there is already a volta configuration within the core package, it serves commands such as `build` and `starter`, however the root package.json from this repository is used to install, so the volta configuration is crucial here too , as yarn must be correctly configured in advance.
=> fix: volta settings

package.json, yarn.lock
Remove explicit dependency from @faststore/core in favor of depending only on @faststore/cli
The new version of the CLI now depends on core, instead of the other way around, so having the explicit dependency on faststore/cli is enough now, instead of having both.
Everything should work the same on the build
=> Bump cli version

package.json, yarn.lock
Removes lighthouse as dev dependency and updates `@faststore/cli` version
Everything should be the same. No changes in the application.
https://github.com/vtex/faststore/pull/2456
=> chore: Removes lighthouse as dev dependency

package.json, yarn.lock
Adds the following changes:
[7948467](https://github.com/vtex/faststore/commit/7948467a59991fc417358a4df3d8d3e330977dd9) [no ci] Release: 3.0.114
[2a8eade](https://github.com/vtex/faststore/commit/2a8eade90764815bb64229c9530a70f569000f3c) Feat: Promise.all homepage and global Promises ([#2471](https://redirect.github.com/vtex/faststore/issues/2471))
[47915ea](https://github.com/vtex/faststore/commit/47915eac24beec2aea06c244ef931500bac2f8de) [no ci] Release: 3.0.113
[a09f274](https://github.com/vtex/faststore/commit/a09f274de317b686b4956bf84e25f26e5dafa50d) feat: removes nextjs-progressbar and chalk ([#2469](https://redirect.github.com/vtex/faststore/issues/2469))
=> Chore: Updates @faststore/cli from 3.0.112 to 3.0.114 

faststore.config.js, package.json, yarn.lock
Adds the following changes:
[1cc987d](https://github.com/vtex/faststore/commit/1cc987d52dfce0b3235e80662099a55c7acb9ba9) [no ci] Release: 3.0.115
[2d6d89e](https://github.com/vtex/faststore/commit/2d6d89e4f95fa7a6ea12ca6d873b186ca3d8f637) Fix: Integration and enable back accessibility tests ([#2458](https://redirect.github.com/vtex/faststore/issues/2458))
Updates the PDP product path in `faststore.config.js`
Note:
Unfortunately, these accessibility testes are failing again, although it was passing before. We'll fix it in another version and proceed with this update.
=> Fix: Integration and enable back accessibility tests - Updates @faststore/cli to 3.0.115

discovery.config.js
Follow the [FastStore doc](https://developers.vtex.com/docs/guides/faststore/go-live-1-configuring-external-dns#step-4-associating-your-custom-domain-with-your-faststore-project). The `storeUrl` in `discovery.config.js` file should already include the subdomain, which the starter wasn't doing.
Navigate through the preview, the store's behavior shouldn't have changed.
=> fix: Add www to storeUrl
